services:
  db:
    container_name: movie-app-db
    image: mysql:8.2.0
    command: --default-authentication-plugin=caching_sha2_password
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: 8d49945f4b59b7511019ec0ea3dd61f650f6c8b9877268d04ff6d02d13bcd267
      MYSQL_DATABASE: movie_app
      MYSQL_USER: user_0
      MYSQL_PASSWORD: d01b172a7d06dd91805e0c9d72cbc21102d3233ac32bece40036ec0368df2f8a
    ports:
      - 3306:3306
    volumes:
      - db_data:/etc/mysql/db_data
    networks:
      - db_network
  # be:
  #   container_name: movie-app-be
  #   build: ./be
  #   ports:
  #     - 8000:8000
  #   depends_on:
  #     - db
  #   networks:
  #     - db_network
networks:
  db_network: 
    driver: bridge
volumes:
  db_data:

