export const homeData = [
    {
      id: 1,
      name: "Phim 1",
      rating: 5,
      time: "1h  22'",
      desc: "Giới thiệu phim ....",
      genres: "Action",
      tags: "Thể thao",
      cover: "https://i3.ytimg.com/vi/1f_LwO9wKK0/maxresdefault.jpg",
      video: "https://www.youtube.com/embed/1f_LwO9wKK0",
      date: "20-Jan-1997",
    },
    {
      id: 2,
      name: "Phim 2",
      rating: 5,
      time: "2hr : 22mins",
      desc: "Phim 2",
      genres: "Action",
      tags: "Action, Adventures, Horror",
      cover: "https://i3.ytimg.com/vi/1f_LwO9wKK0/maxresdefault.jpg",
      video: "https://www.youtube.com/embed/1f_LwO9wKK0",
      date: "20-Jan-1997",
    },
    {
      id: 3,
      name: "Phim 3",
      rating: 5,
      time: "2hr : 22mins",
      desc: "Phim 3",
      genres: "Action",
      tags: "Action, Adventures, Horror",
      cover: "https://i3.ytimg.com/vi/1f_LwO9wKK0/maxresdefault.jpg",
      video: "https://www.youtube.com/embed/1f_LwO9wKK0",
      date: "20-Jan-1997",
    },
    {
      id: 4,
      name: "Phim 4",
      rating: 5,
      time: "2hr : 22mins",
      desc: "Phim 4",
      genres: "Action",
      tags: "Action, Adventures, Horror",
      cover: "https://i3.ytimg.com/vi/1f_LwO9wKK0/maxresdefault.jpg",
      video: "https://www.youtube.com/embed/1f_LwO9wKK0",
      date: "20-Jan-1997",
    },
  ]
  export const sport = [
    {
      id: 1,
      cover: "https://i3.ytimg.com/vi/1f_LwO9wKK0/maxresdefault.jpg",
      name: "Thể thao 1",
      time: "2hr : 38mins",
    },
    {
      id: 2,
      cover: "https://i3.ytimg.com/vi/1f_LwO9wKK0/maxresdefault.jpg",
      name: "Thể thao 2",
      time: "2hr : 38mins",
    },
    {
      id: 3,
      cover: "https://i3.ytimg.com/vi/1f_LwO9wKK0/maxresdefault.jpg",
      name: "Thể thao 3",
      time: "2hr : 38mins",
    },
    {
      id: 4,
      cover: "https://i3.ytimg.com/vi/1f_LwO9wKK0/maxresdefault.jpg",
      name: "Thể thao 4",
      time: "2hr : 38mins",
    },
    {
      id: 5,
      cover: "https://i3.ytimg.com/vi/1f_LwO9wKK0/maxresdefault.jpg",
      name: "Thể thao 5",
      time: "2hr : 38mins",
    },
    {
      id: 6,
      cover: "https://i3.ytimg.com/vi/1f_LwO9wKK0/maxresdefault.jpg",
      name: "Thể thao 6",
      time: "2hr : 38mins",
    },
    {
      id: 7,
      cover: "https://i3.ytimg.com/vi/1f_LwO9wKK0/maxresdefault.jpg",
      name: "Thể thao 7",
      time: "2hr : 38mins",
    },
    {
      id: 8,
      cover: "https://i3.ytimg.com/vi/1f_LwO9wKK0/maxresdefault.jpg",
      name: "Thể thao 8",
      time: "2hr : 38mins",
    },
    {
      id: 9,
      cover: "https://i3.ytimg.com/vi/1f_LwO9wKK0/maxresdefault.jpg",
      name: "Thể thao 9",
      time: "2hr : 38mins",
    },
    {
      id: 10,
      cover: "https://i3.ytimg.com/vi/1f_LwO9wKK0/maxresdefault.jpg",
      name: "Thể thao 10",
      time: "2hr : 38mins",
    },
    {
      id: 11,
      cover: "https://i3.ytimg.com/vi/1f_LwO9wKK0/maxresdefault.jpg",
      name: "Thể thao 11",
      time: "2hr : 38mins",
    },
    {
      id: 12,
      cover: "https://i3.ytimg.com/vi/1f_LwO9wKK0/maxresdefault.jpg",
      name: "Thể thao 12",
      time: "2hr : 38mins",
    },
    {
      id: 13,
      cover: "https://i3.ytimg.com/vi/1f_LwO9wKK0/maxresdefault.jpg",
      name: "Thể thao 13",
      time: "2hr : 38mins",
    },
    {
      id: 14,
      cover: "https://i3.ytimg.com/vi/1f_LwO9wKK0/maxresdefault.jpg",
      name: "Thể thao 14",
      time: "2hr : 38mins",
    },
    {
      id: 15,
      cover: "https://i3.ytimg.com/vi/1f_LwO9wKK0/maxresdefault.jpg",
      name: "Thể thao 15",
      time: "2hr : 38mins",
    },
    {
      id: 16,
      cover: "https://i3.ytimg.com/vi/1f_LwO9wKK0/maxresdefault.jpg",
      name: "Thể thao 16",
      time: "2hr : 38mins",
    },
    {
      id: 17,
      cover: "https://i3.ytimg.com/vi/1f_LwO9wKK0/maxresdefault.jpg",
      name: "Thể thao 17",
      time: "2hr : 38mins",
    },
    {
      id: 18,
      cover: "https://i3.ytimg.com/vi/1f_LwO9wKK0/maxresdefault.jpg",
      name: "Thể thao 18",
      time: "2hr : 38mins",
    },
    {
      id: 19,
      cover: "https://i3.ytimg.com/vi/1f_LwO9wKK0/maxresdefault.jpg",
      name: "Thể thao 19",
      time: "2hr : 38mins",
    },
    {
      id: 20,
      cover: "https://i3.ytimg.com/vi/1f_LwO9wKK0/maxresdefault.jpg",
      name: "Thể thao 20",
      time: "2hr : 38mins",
    },
    {
      id: 21,
      cover: "https://i3.ytimg.com/vi/1f_LwO9wKK0/maxresdefault.jpg",
      name: "Thể thao 21",
      time: "2hr : 38mins",
    },
    {
      id: 22,
      cover: "https://i3.ytimg.com/vi/1f_LwO9wKK0/maxresdefault.jpg",
      name: "Thể thao 22",
      time: "2hr : 38mins",
    },
    {
      id: 23,
      cover: "https://i3.ytimg.com/vi/1f_LwO9wKK0/maxresdefault.jpg",
      name: "Thể thao 23",
      time: "2hr : 38mins",
    },
    {
      id: 24,
      cover: "https://i3.ytimg.com/vi/1f_LwO9wKK0/maxresdefault.jpg",
      name: "Thể thao 24",
      time: "2hr : 38mins",
    },
    {
      id: 25,
      cover: "https://i3.ytimg.com/vi/1f_LwO9wKK0/maxresdefault.jpg",
      name: "Thể thao 25",
      time: "2hr : 38mins",
    },
    {
      id: 26,
      cover: "https://i3.ytimg.com/vi/1f_LwO9wKK0/maxresdefault.jpg",
      name: "Thể thao 26",
      time: "2hr : 38mins",
    },
    {
      id: 27,
      cover: "https://i3.ytimg.com/vi/1f_LwO9wKK0/maxresdefault.jpg",
      name: "Thể thao 27",
      time: "2hr : 38mins",
    },
    {
      id: 28,
      cover: "https://i3.ytimg.com/vi/1f_LwO9wKK0/maxresdefault.jpg",
      name: "Thể thao 28",
      time: "2hr : 38mins",
    },
    {
      id: 29,
      cover: "https://i3.ytimg.com/vi/1f_LwO9wKK0/maxresdefault.jpg",
      name: "Thể thao 29",
      time: "2hr : 38mins",
    },
    {
      id: 30,
      cover: "https://i3.ytimg.com/vi/1f_LwO9wKK0/maxresdefault.jpg",
      name: "Thể thao 30",
      time: "2hr : 38mins",
    },
  ]
  export const music = [
    {
      id: 1,
      cover: "https://i3.ytimg.com/vi/1f_LwO9wKK0/maxresdefault.jpg",
      name: "nhạc 1",
      time: "2hr : 38mins",
    },
    {
      id: 2,
      cover: "https://i3.ytimg.com/vi/1f_LwO9wKK0/maxresdefault.jpg",
      name: "nhạc 2",
      time: "2hr : 38mins",
    },
    {
      id: 3,
      cover: "https://i3.ytimg.com/vi/1f_LwO9wKK0/maxresdefault.jpg",
      name: "nhạc 3",
      time: "2hr : 38mins",
    },
    {
      id: 4,
      cover: "https://i3.ytimg.com/vi/1f_LwO9wKK0/maxresdefault.jpg",
      name: "nhạc 4",
      time: "2hr : 38mins",
    },
    {
      id: 5,
      cover: "https://i3.ytimg.com/vi/1f_LwO9wKK0/maxresdefault.jpg",
      name: "nhạc 5",
      time: "2hr : 38mins",
    },
  ]
  
  export const recommended = [
    {
      id: 1,
      name: "Du lịch 1",
      rating: 5,
      time: "2hr : 22mins",
      desc: "Du lịch 1",
      genres: "Action",
      tags: "Action, Adventures, Horror",
      cover: "https://i3.ytimg.com/vi/1f_LwO9wKK0/maxresdefault.jpg",
      video: "../video/temp.mp4",
      date: "20-Jan-1997",
    },
    {
      id: 2,
      name: "Du lịch 2",
      rating: 5,
      time: "2hr : 22mins",
      desc: "Du lịch 2",
      genres: "Action",
      tags: "Action, Adventures, Horror",
      cover: "https://i3.ytimg.com/vi/1f_LwO9wKK0/maxresdefault.jpg",
      video: "../video/temp.mp4",
      date: "20-Jan-1997",
    },
    {
      id: 3,
      name: "Du lịch 3",
      rating: 5,
      time: "2hr : 22mins",
      desc: "Du lịch 3",
      genres: "Action",
      tags: "Action, Adventures, Horror",
      cover: "https://i3.ytimg.com/vi/1f_LwO9wKK0/maxresdefault.jpg",
      video: "../video/temp.mp4",
      date: "20-Jan-1997",
    },
    {
      id: 4,
      name: "Du lịch 4",
      rating: 5,
      time: "2hr : 22mins",
      desc: "Du lịch 4",
      genres: "Action",
      tags: "Action, Adventures, Horror",
      cover: "https://i3.ytimg.com/vi/1f_LwO9wKK0/maxresdefault.jpg",
      video: "../video/temp.mp4",
      date: "20-Jan-1997",
    },
  ]
  export const travel = [
    {
      id: 1,
      cover: "https://i3.ytimg.com/vi/1f_LwO9wKK0/maxresdefault.jpg",
      name: "movie 1",
      time: "2hr : 38mins",
    },
    {
      id: 2,
      cover: "https://i3.ytimg.com/vi/1f_LwO9wKK0/maxresdefault.jpg",
      name: "movie 2",
      time: "2hr : 38mins",
    },
    {
      id: 3,
      cover: "https://i3.ytimg.com/vi/1f_LwO9wKK0/maxresdefault.jpg",
      name: "movie 3",
      time: "2hr : 38mins",
    },
    {
      id: 4,
      cover: "https://i3.ytimg.com/vi/1f_LwO9wKK0/maxresdefault.jpg",
      name: "movie 4",
      time: "2hr : 38mins",
    },
    {
      id: 5,
      cover: "https://i3.ytimg.com/vi/1f_LwO9wKK0/maxresdefault.jpg",
      name: "movie 5",
      time: "2hr : 38mins",
    },
  ]