export const homeData = [
    {
      id: 1,
      name: "Movie 1",
      rating: 5,
      time: "2hr : 22mins",
      desc: "Movie 1",
      genres: "Action",
      tags: "Action, Adventures, Horror",
      cover: "../images/temp.jpg",
      video: "../video/temp.mp4",
      date: "20-Jan-1997",
    },
    {
      id: 2,
      name: "Movie 2",
      rating: 5,
      time: "2hr : 22mins",
      desc: "Movie 2",
      genres: "Action",
      tags: "Action, Adventures, Horror",
      cover: "../images/temp.jpg",
      video: "../video/temp.mp4",
      date: "20-Jan-1997",
    },
    {
      id: 3,
      name: "Movie 3",
      rating: 5,
      time: "2hr : 22mins",
      desc: "Movie 3",
      genres: "Action",
      tags: "Action, Adventures, Horror",
      cover: "../images/temp.jpg",
      video: "../video/temp.mp4",
      date: "20-Jan-1997",
    },
    {
      id: 4,
      name: "Movie 4",
      rating: 5,
      time: "2hr : 22mins",
      desc: "Movie 4",
      genres: "Action",
      tags: "Action, Adventures, Horror",
      cover: "../images/temp.jpg",
      video: "../video/temp.mp4",
      date: "20-Jan-1997",
    },
  ]
  export const upcome = [
    {
      id: 1,
      cover: "../images/temp.jpg",
      name: "movie 1",
      time: "2hr : 38mins",
    },
    {
      id: 2,
      cover: "../images/temp.jpg",
      name: "movie 2",
      time: "2hr : 38mins",
    },
    {
      id: 3,
      cover: "../images/temp.jpg",
      name: "movie 3",
      time: "2hr : 38mins",
    },
    {
      id: 4,
      cover: "../images/temp.jpg",
      name: "movie 4",
      time: "2hr : 38mins",
    },
    {
      id: 5,
      cover: "../images/temp.jpg",
      name: "movie 5",
      time: "2hr : 38mins",
    },
  ]
  export const latest = [
    {
      id: 1,
      cover: "../images/temp.jpg",
      name: "movie 1",
      time: "2hr : 38mins",
    },
    {
      id: 2,
      cover: "../images/temp.jpg",
      name: "movie 2",
      time: "2hr : 38mins",
    },
    {
      id: 3,
      cover: "../images/temp.jpg",
      name: "movie 3",
      time: "2hr : 38mins",
    },
    {
      id: 4,
      cover: "../images/temp.jpg",
      name: "movie 4",
      time: "2hr : 38mins",
    },
    {
      id: 5,
      cover: "../images/temp.jpg",
      name: "movie 5",
      time: "2hr : 38mins",
    },
  ]
  
  export const trending = [
    {
      id: 1,
      name: "Movie 1",
      rating: 5,
      time: "2hr : 22mins",
      desc: "Movie 1",
      genres: "Action",
      tags: "Action, Adventures, Horror",
      cover: "../images/temp.jpg",
      video: "../video/temp.mp4",
      date: "20-Jan-1997",
    },
    {
      id: 2,
      name: "Movie 2",
      rating: 5,
      time: "2hr : 22mins",
      desc: "Movie 2",
      genres: "Action",
      tags: "Action, Adventures, Horror",
      cover: "../images/temp.jpg",
      video: "../video/temp.mp4",
      date: "20-Jan-1997",
    },
    {
      id: 3,
      name: "Movie 3",
      rating: 5,
      time: "2hr : 22mins",
      desc: "Movie 3",
      genres: "Action",
      tags: "Action, Adventures, Horror",
      cover: "../images/temp.jpg",
      video: "../video/temp.mp4",
      date: "20-Jan-1997",
    },
    {
      id: 4,
      name: "Movie 4",
      rating: 5,
      time: "2hr : 22mins",
      desc: "Movie 4",
      genres: "Action",
      tags: "Action, Adventures, Horror",
      cover: "../images/temp.jpg",
      video: "../video/temp.mp4",
      date: "20-Jan-1997",
    },
  ]
  export const recommended = [
    {
      id: 1,
      cover: "../images/temp.jpg",
      name: "movie 1",
      time: "2hr : 38mins",
    },
    {
      id: 2,
      cover: "../images/temp.jpg",
      name: "movie 2",
      time: "2hr : 38mins",
    },
    {
      id: 3,
      cover: "../images/temp.jpg",
      name: "movie 3",
      time: "2hr : 38mins",
    },
    {
      id: 4,
      cover: "../images/temp.jpg",
      name: "movie 4",
      time: "2hr : 38mins",
    },
    {
      id: 5,
      cover: "../images/temp.jpg",
      name: "movie 5",
      time: "2hr : 38mins",
    },
  ]