export const homeData = [
    {
      id: 1,
      name: "Thể thao 1",
      rating: 4.5,
      time: "1h  22'",
      desc: "Giới thiệu phim ....",
      tags: "Thể thao",
      cover: "https://i3.ytimg.com/vi/76G8BDpgWu0/maxresdefault.jpg",
      video: "https://www.youtube.com/embed/76G8BDpgWu0",
      date: "20-1-2010",
    },
    {
      id: 2,
      name: "Thể thao 2",
      rating: 5,
      time: "2hr : 22mins",
      desc: "Phim 2",
      tags: "Thể thao",
      cover: "https://i3.ytimg.com/vi/76G8BDpgWu0/maxresdefault.jpg",
      video: "https://www.youtube.com/embed/76G8BDpgWu0",
      date: "20-1-2010",
    },
    {
      id: 3,
      name: "Thể thao 3",
      rating: 5,
      time: "2hr : 22mins",
      desc: "Phim 3",
      tags: "Thể thao",
      cover: "https://i3.ytimg.com/vi/76G8BDpgWu0/maxresdefault.jpg",
      video: "https://www.youtube.com/embed/76G8BDpgWu0",
      date: "20-1-2010",
    },
    {
      id: 4,
      name: "Thể thao 4",
      rating: 5,
      time: "2hr : 22mins",
      desc: "Phim 4",
      tags: "Thể thao",
      cover: "https://i3.ytimg.com/vi/76G8BDpgWu0/maxresdefault.jpg",
      video: "https://www.youtube.com/embed/76G8BDpgWu0",
      date: "20-1-2010",
    },
    {
      id: 5,
      name: "Thể thao 5",
      rating: 4.5,
      time: "1h  22'",
      desc: "Giới thiệu phim ....",
      tags: "Thể thao",
      cover: "https://i3.ytimg.com/vi/76G8BDpgWu0/maxresdefault.jpg",
      video: "https://www.youtube.com/embed/76G8BDpgWu0",
      date: "20-1-2010",
    },
    {
      id: 6,
      name: "Thể thao 6",
      rating: 5,
      time: "2hr : 22mins",
      desc: "Phim 2",
      tags: "Thể thao",
      cover: "https://i3.ytimg.com/vi/76G8BDpgWu0/maxresdefault.jpg",
      video: "https://www.youtube.com/embed/76G8BDpgWu0",
      date: "20-1-2010",
    },
    {
      id: 7,
      name: "Thể thao 7",
      rating: 5,
      time: "2hr : 22mins",
      desc: "Phim 3",
      tags: "Thể thao",
      cover: "https://i3.ytimg.com/vi/76G8BDpgWu0/maxresdefault.jpg",
      video: "https://www.youtube.com/embed/76G8BDpgWu0",
      date: "20-1-2010",
    },
    {
      id: 8,
      name: "Thể thao 8",
      rating: 5,
      time: "2hr : 22mins",
      desc: "Phim 4",
      tags: "Thể thao",
      cover: "https://i3.ytimg.com/vi/76G8BDpgWu0/maxresdefault.jpg",
      video: "https://www.youtube.com/embed/76G8BDpgWu0",
      date: "20-1-2010",
    },
    {
      id: 9,
      name: "Thể thao 9",
      rating: 5,
      time: "2hr : 22mins",
      desc: "Phim 3",
      tags: "Thể thao",
      cover: "https://i3.ytimg.com/vi/76G8BDpgWu0/maxresdefault.jpg",
      video: "https://www.youtube.com/embed/76G8BDpgWu0",
      date: "20-1-2010",
    },
    {
      id: 10,
      name: "Thể thao 10",
      rating: 5,
      time: "2hr : 22mins",
      desc: "Phim 4",
      tags: "Thể thao",
      cover: "https://i3.ytimg.com/vi/76G8BDpgWu0/maxresdefault.jpg",
      video: "https://www.youtube.com/embed/76G8BDpgWu0",
      date: "20-1-2010",
    },
    {
      id: 11,
      name: "Thể thao 11",
      rating: 4.5,
      time: "1h  22'",
      desc: "Giới thiệu phim ....",
      tags: "Thể thao",
      cover: "https://i3.ytimg.com/vi/76G8BDpgWu0/maxresdefault.jpg",
      video: "https://www.youtube.com/embed/76G8BDpgWu0",
      date: "20-1-2010",
    },
    {
      id: 12,
      name: "Thể thao 12",
      rating: 5,
      time: "2hr : 22mins",
      desc: "Phim 2",
      tags: "Thể thao",
      cover: "https://i3.ytimg.com/vi/76G8BDpgWu0/maxresdefault.jpg",
      video: "https://www.youtube.com/embed/76G8BDpgWu0",
      date: "20-1-2010",
    },
    {
      id: 13,
      name: "Thể thao 13",
      rating: 5,
      time: "2hr : 22mins",
      desc: "Phim 3",
      tags: "Thể thao",
      cover: "https://i3.ytimg.com/vi/76G8BDpgWu0/maxresdefault.jpg",
      video: "https://www.youtube.com/embed/76G8BDpgWu0",
      date: "20-1-2010",
    },
    {
      id: 14,
      name: "Thể thao 14",
      rating: 5,
      time: "2hr : 22mins",
      desc: "Phim 4",
      tags: "Thể thao",
      cover: "https://i3.ytimg.com/vi/76G8BDpgWu0/maxresdefault.jpg",
      video: "https://www.youtube.com/embed/76G8BDpgWu0",
      date: "20-1-2010",
    },
    {
      id: 15,
      name: "Thể thao 15",
      rating: 4.5,
      time: "1h  22'",
      desc: "Giới thiệu phim ....",
      tags: "Thể thao",
      cover: "https://i3.ytimg.com/vi/76G8BDpgWu0/maxresdefault.jpg",
      video: "https://www.youtube.com/embed/76G8BDpgWu0",
      date: "20-1-2010",
    },
    {
      id: 16,
      name: "Thể thao 16",
      rating: 5,
      time: "2hr : 22mins",
      desc: "Phim 2",
      tags: "Thể thao",
      cover: "https://i3.ytimg.com/vi/76G8BDpgWu0/maxresdefault.jpg",
      video: "https://www.youtube.com/embed/76G8BDpgWu0",
      date: "20-1-2010",
    },
    {
      id: 17,
      name: "Thể thao 17",
      rating: 5,
      time: "2hr : 22mins",
      desc: "Phim 3",
      tags: "Thể thao",
      cover: "https://i3.ytimg.com/vi/76G8BDpgWu0/maxresdefault.jpg",
      video: "https://www.youtube.com/embed/76G8BDpgWu0",
      date: "20-1-2010",
    },
    {
      id: 18,
      name: "Thể thao 18",
      rating: 5,
      time: "2hr : 22mins",
      desc: "Phim 4",
      tags: "Thể thao",
      cover: "https://i3.ytimg.com/vi/76G8BDpgWu0/maxresdefault.jpg",
      video: "https://www.youtube.com/embed/76G8BDpgWu0",
      date: "20-1-2010",
    },
    {
      id: 19,
      name: "Thể thao 19",
      rating: 5,
      time: "2hr : 22mins",
      desc: "Phim 3",
      tags: "Thể thao",
      cover: "https://i3.ytimg.com/vi/76G8BDpgWu0/maxresdefault.jpg",
      video: "https://www.youtube.com/embed/76G8BDpgWu0",
      date: "20-1-2010",
    },
    {
      id: 20,
      name: "Thể thao 20",
      rating: 5,
      time: "2hr : 22mins",
      desc: "Phim 4",
      tags: "Thể thao",
      cover: "https://i3.ytimg.com/vi/76G8BDpgWu0/maxresdefault.jpg",
      video: "https://www.youtube.com/embed/76G8BDpgWu0",
      date: "20-1-2010",
    },
    {
      id: 21,
      name: "Thể thao 21",
      rating: 4.5,
      time: "1h  22'",
      desc: "Giới thiệu phim ....",
      tags: "Thể thao",
      cover: "https://i3.ytimg.com/vi/76G8BDpgWu0/maxresdefault.jpg",
      video: "https://www.youtube.com/embed/76G8BDpgWu0",
      date: "20-1-2010",
    },
    {
      id: 22,
      name: "Thể thao 22",
      rating: 5,
      time: "2hr : 22mins",
      desc: "Phim 2",
      tags: "Thể thao",
      cover: "https://i3.ytimg.com/vi/76G8BDpgWu0/maxresdefault.jpg",
      video: "https://www.youtube.com/embed/76G8BDpgWu0",
      date: "20-1-2010",
    },
    {
      id: 23,
      name: "Thể thao 23",
      rating: 5,
      time: "2hr : 22mins",
      desc: "Phim 3",
      tags: "Thể thao",
      cover: "https://i3.ytimg.com/vi/76G8BDpgWu0/maxresdefault.jpg",
      video: "https://www.youtube.com/embed/76G8BDpgWu0",
      date: "20-1-2010",
    },
    {
      id: 24,
      name: "Thể thao 24",
      rating: 5,
      time: "2hr : 22mins",
      desc: "Phim 4",
      tags: "Thể thao",
      cover: "https://i3.ytimg.com/vi/76G8BDpgWu0/maxresdefault.jpg",
      video: "https://www.youtube.com/embed/76G8BDpgWu0",
      date: "20-1-2010",
    },
    {
      id: 25,
      name: "Thể thao 25",
      rating: 4.5,
      time: "1h  22'",
      desc: "Giới thiệu phim ....",
      tags: "Thể thao",
      cover: "https://i3.ytimg.com/vi/76G8BDpgWu0/maxresdefault.jpg",
      video: "https://www.youtube.com/embed/76G8BDpgWu0",
      date: "20-1-2010",
    },
    {
      id: 26,
      name: "Thể thao 26",
      rating: 5,
      time: "2hr : 22mins",
      desc: "Phim 2",
      tags: "Thể thao",
      cover: "https://i3.ytimg.com/vi/76G8BDpgWu0/maxresdefault.jpg",
      video: "https://www.youtube.com/embed/76G8BDpgWu0",
      date: "20-1-2010",
    },
    {
      id: 27,
      name: "Thể thao 27",
      rating: 5,
      time: "2hr : 22mins",
      desc: "Phim 3",
      tags: "Thể thao",
      cover: "https://i3.ytimg.com/vi/76G8BDpgWu0/maxresdefault.jpg",
      video: "https://www.youtube.com/embed/76G8BDpgWu0",
      date: "20-1-2010",
    },
    {
      id: 28,
      name: "Thể thao 28",
      rating: 5,
      time: "2hr : 22mins",
      desc: "Phim 4",
      tags: "Thể thao",
      cover: "https://i3.ytimg.com/vi/76G8BDpgWu0/maxresdefault.jpg",
      video: "https://www.youtube.com/embed/76G8BDpgWu0",
      date: "20-1-2010",
    },
    {
      id: 29,
      name: "Thể thao 29",
      rating: 5,
      time: "2hr : 22mins",
      desc: "Phim 3",
      tags: "Thể thao",
      cover: "https://i3.ytimg.com/vi/76G8BDpgWu0/maxresdefault.jpg",
      video: "https://www.youtube.com/embed/76G8BDpgWu0",
      date: "20-1-2010",
    },
    {
      id: 30,
      name: "Thể thao 30",
      rating: 5,
      time: "2hr : 22mins",
      desc: "Phim 4",
      tags: "Thể thao",
      cover: "https://i3.ytimg.com/vi/76G8BDpgWu0/maxresdefault.jpg",
      video: "https://www.youtube.com/embed/76G8BDpgWu0",
      date: "20-1-2010",
    },
    {
      id: 31,
      name: "Flower Dance",
      rating: 4.5,
      time: "1h  22'",
      desc: "Giới thiệu phim ....",
      tags: "Âm nhạc",
      cover: "https://i3.ytimg.com/vi/3wh2SbSEmh0/maxresdefault.jpg",
      video: "https://www.youtube.com/embed/3wh2SbSEmh0",
      date: "20-1-2010",
    },
    {
      id: 32,
      name: "Flower Dance",
      rating: 5,
      time: "2hr : 22mins",
      desc: "Flower Dance desc",
      tags: "Âm nhạc",
      cover: "https://i3.ytimg.com/vi/3wh2SbSEmh0/maxresdefault.jpg",
      video: "https://www.youtube.com/embed/3wh2SbSEmh0",
      date: "20-1-2010",
    },
    {
      id: 33,
      name: "Flower Dance",
      rating: 5,
      time: "2hr : 22mins",
      desc: "Phim 3",
      tags: "Âm nhạc",
      cover: "https://i3.ytimg.com/vi/3wh2SbSEmh0/maxresdefault.jpg",
      video: "https://www.youtube.com/embed/3wh2SbSEmh0",
      date: "20-1-2010",
    },
    {
      id: 34,
      name: "Flower Dance",
      rating: 5,
      time: "2hr : 22mins",
      desc: "Phim 4",
      tags: "Âm nhạc",
      cover: "https://i3.ytimg.com/vi/3wh2SbSEmh0/maxresdefault.jpg",
      video: "https://www.youtube.com/embed/3wh2SbSEmh0",
      date: "20-1-2010",
    },
    {
      id: 35,
      name: "Flower Dance",
      rating: 4.5,
      time: "1h  22'",
      desc: "Giới thiệu phim ....",
      tags: "Âm nhạc",
      cover: "https://i3.ytimg.com/vi/3wh2SbSEmh0/maxresdefault.jpg",
      video: "https://www.youtube.com/embed/3wh2SbSEmh0",
      date: "20-1-2010",
    },
    {
      id: 36,
      name: "du lịch 1",
      rating: 5,
      time: "2hr : 22mins",
      desc: "Phim 2",
      tags: "Du lịch",
      cover: "https://i3.ytimg.com/vi/kZN2yTa1HcY/maxresdefault.jpg",
      video: "https://www.youtube.com/embed/kZN2yTa1HcY",
      date: "20-1-2010",
    },
    {
      id: 37,
      name: "du lịch 2",
      rating: 5,
      time: "2hr : 22mins",
      desc: "Phim 3",
      tags: "Du lịch",
      cover: "https://i3.ytimg.com/vi/kZN2yTa1HcY/maxresdefault.jpg",
      video: "https://www.youtube.com/embed/kZN2yTa1HcY",
      date: "20-1-2010",
    },
    {
      id: 38,
      name: "du lịch 3",
      rating: 5,
      time: "2hr : 22mins",
      desc: "Phim 4",
      tags: "Du lịch",
      cover: "https://i3.ytimg.com/vi/kZN2yTa1HcY/maxresdefault.jpg",
      video: "https://www.youtube.com/embed/kZN2yTa1HcY",
      date: "20-1-2010",
    },
    {
      id: 39,
      name: "du lịch 4",
      rating: 5,
      time: "2hr : 22mins",
      desc: "Phim 3",
      tags: "Du lịch",
      cover: "https://i3.ytimg.com/vi/kZN2yTa1HcY/maxresdefault.jpg",
      video: "https://www.youtube.com/embed/kZN2yTa1HcY",
      date: "20-1-2010",
    },
    {
      id: 40,
      name: "du lịch 5",
      rating: 5,
      time: "2hr : 22mins",
      desc: "Phim 4",
      tags: "Du lịch",
      cover: "https://i3.ytimg.com/vi/kZN2yTa1HcY/maxresdefault.jpg",
      video: "https://www.youtube.com/embed/kZN2yTa1HcY",
      date: "20-1-2010",
    }
  ]
  export const sport = [
    {
      id: 1,
      cover: "https://i3.ytimg.com/vi/76G8BDpgWu0/maxresdefault.jpg",
      name: "Thể thao 1",
    },
    {
      id: 2,
      cover: "https://i3.ytimg.com/vi/76G8BDpgWu0/maxresdefault.jpg",
      name: "Thể thao 2",
    },
    {
      id: 3,
      cover: "https://i3.ytimg.com/vi/76G8BDpgWu0/maxresdefault.jpg",
      name: "Thể thao 3",
    },
    {
      id: 4,
      cover: "https://i3.ytimg.com/vi/76G8BDpgWu0/maxresdefault.jpg",
      name: "Thể thao 4",
    },
    {
      id: 5,
      cover: "https://i3.ytimg.com/vi/76G8BDpgWu0/maxresdefault.jpg",
      name: "Thể thao 5",
    },
    {
      id: 6,
      cover: "https://i3.ytimg.com/vi/76G8BDpgWu0/maxresdefault.jpg",
      name: "Thể thao 6",
    },
    {
      id: 7,
      cover: "https://i3.ytimg.com/vi/76G8BDpgWu0/maxresdefault.jpg",
      name: "Thể thao 7",
    },
    {
      id: 8,
      cover: "https://i3.ytimg.com/vi/76G8BDpgWu0/maxresdefault.jpg",
      name: "Thể thao 8",
    },
    {
      id: 9,
      cover: "https://i3.ytimg.com/vi/76G8BDpgWu0/maxresdefault.jpg",
      name: "Thể thao 9",
    },
    {
      id: 10,
      cover: "https://i3.ytimg.com/vi/76G8BDpgWu0/maxresdefault.jpg",
      name: "Thể thao 10",
    },
    {
      id: 11,
      cover: "https://i3.ytimg.com/vi/76G8BDpgWu0/maxresdefault.jpg",
      name: "Thể thao 11",
    },
    {
      id: 12,
      cover: "https://i3.ytimg.com/vi/76G8BDpgWu0/maxresdefault.jpg",
      name: "Thể thao 12",
    },
    {
      id: 13,
      cover: "https://i3.ytimg.com/vi/76G8BDpgWu0/maxresdefault.jpg",
      name: "Thể thao 13",
    },
    {
      id: 14,
      cover: "https://i3.ytimg.com/vi/76G8BDpgWu0/maxresdefault.jpg",
      name: "Thể thao 14",
    },
    {
      id: 15,
      cover: "https://i3.ytimg.com/vi/76G8BDpgWu0/maxresdefault.jpg",
      name: "Thể thao 15",
    },
    {
      id: 16,
      cover: "https://i3.ytimg.com/vi/76G8BDpgWu0/maxresdefault.jpg",
      name: "Thể thao 16",
    },
    {
      id: 17,
      cover: "https://i3.ytimg.com/vi/76G8BDpgWu0/maxresdefault.jpg",
      name: "Thể thao 17",
    },
    {
      id: 18,
      cover: "https://i3.ytimg.com/vi/76G8BDpgWu0/maxresdefault.jpg",
      name: "Thể thao 18",
    },
    {
      id: 19,
      cover: "https://i3.ytimg.com/vi/76G8BDpgWu0/maxresdefault.jpg",
      name: "Thể thao 19",
    },
    {
      id: 20,
      cover: "https://i3.ytimg.com/vi/76G8BDpgWu0/maxresdefault.jpg",
      name: "Thể thao 20",
    },
    {
      id: 21,
      cover: "https://i3.ytimg.com/vi/76G8BDpgWu0/maxresdefault.jpg",
      name: "Thể thao 21",
    },
    {
      id: 22,
      cover: "https://i3.ytimg.com/vi/76G8BDpgWu0/maxresdefault.jpg",
      name: "Thể thao 22",
    },
    {
      id: 23,
      cover: "https://i3.ytimg.com/vi/76G8BDpgWu0/maxresdefault.jpg",
      name: "Thể thao 23",
    },
    {
      id: 24,
      cover: "https://i3.ytimg.com/vi/76G8BDpgWu0/maxresdefault.jpg",
      name: "Thể thao 24",
    },
    {
      id: 25,
      cover: "https://i3.ytimg.com/vi/76G8BDpgWu0/maxresdefault.jpg",
      name: "Thể thao 25",
    },
    {
      id: 26,
      cover: "https://i3.ytimg.com/vi/76G8BDpgWu0/maxresdefault.jpg",
      name: "Thể thao 26",
    },
    {
      id: 27,
      cover: "https://i3.ytimg.com/vi/76G8BDpgWu0/maxresdefault.jpg",
      name: "Thể thao 27",
    },
    {
      id: 28,
      cover: "https://i3.ytimg.com/vi/76G8BDpgWu0/maxresdefault.jpg",
      name: "Thể thao 28",
    },
    {
      id: 29,
      cover: "https://i3.ytimg.com/vi/76G8BDpgWu0/maxresdefault.jpg",
      name: "Thể thao 29",
    },
    {
      id: 30,
      cover: "https://i3.ytimg.com/vi/76G8BDpgWu0/maxresdefault.jpg",
      name: "Thể thao 30",
    },
  ]
  export const music = [
    {
      id: 31,
      cover: "https://i3.ytimg.com/vi/3wh2SbSEmh0/maxresdefault.jpg",
      name: "Flower Dance",
    },
    {
      id: 32,
      cover: "https://i3.ytimg.com/vi/3wh2SbSEmh0/maxresdefault.jpg",
      name: "Flower Dance",
    },
    {
      id: 33,
      cover: "https://i3.ytimg.com/vi/3wh2SbSEmh0/maxresdefault.jpg",
      name: "Flower Dance",
    },
    {
      id: 34,
      cover: "https://i3.ytimg.com/vi/3wh2SbSEmh0/maxresdefault.jpg",
      name: "Flower Dance",
    },
    {
      id: 35,
      cover: "https://i3.ytimg.com/vi/3wh2SbSEmh0/maxresdefault.jpg",
      name: "Flower Dance",
    },
  ]
  
  // export const recommended = [
  //   {
  //     id: 36,
  //     name: "Du lịch 1",
  //     rating: 5,
  //     time: "2hr : 22mins",
  //     desc: "Du lịch 1",
  //     tags: "Action, Adventures, Horror",
  //     cover: "https://i3.ytimg.com/vi/1f_LwO9wKK0/maxresdefault.jpg",
  //     video: "../video/temp.mp4",
  //     date: "20-1-2010",
  //   },
  //   {
  //     id: 37,
  //     name: "Du lịch 2",
  //     rating: 5,
  //     time: "2hr : 22mins",
  //     desc: "Du lịch 2",
  //     tags: "Du lịch",
  //     cover: "https://i3.ytimg.com/vi/1f_LwO9wKK0/maxresdefault.jpg",
  //     video: "../video/temp.mp4",
  //     date: "20-1-2010",
  //   },
  //   {
  //     id: 38,
  //     name: "Du lịch 3",
  //     rating: 5,
  //     time: "2hr : 22mins",
  //     desc: "Du lịch 3",
  //     tags: "Du lịch",
  //     cover: "https://i3.ytimg.com/vi/1f_LwO9wKK0/maxresdefault.jpg",
  //     video: "../video/temp.mp4",
  //     date: "20-1-2010",
  //   },
  //   {
  //     id: 39,
  //     name: "Du lịch 4",
  //     rating: 5,
  //     time: "2hr : 22mins",
  //     desc: "Du lịch 4",
  //     tags: "Du lịch",
  //     cover: "https://i3.ytimg.com/vi/1f_LwO9wKK0/maxresdefault.jpg",
  //     video: "../video/temp.mp4",
  //     date: "20-1-2010",
  //   },
  // ]
  export const travel = [
    {
      id: 40,
      cover: "https://i3.ytimg.com/vi/kZN2yTa1HcY/maxresdefault.jpg",
      name: "du lịch 1",
    },
    {
      id: 41,
      cover: "https://i3.ytimg.com/vi/kZN2yTa1HcY/maxresdefault.jpg",
      name: "du lịch 2",
    },
    {
      id: 42,
      cover: "https://i3.ytimg.com/vi/kZN2yTa1HcY/maxresdefault.jpg",
      name: "du lịch 3",
    },
    {
      id: 43,
      cover: "https://i3.ytimg.com/vi/kZN2yTa1HcY/maxresdefault.jpg",
      name: "du lịch 4",
    },
    {
      id: 44,
      cover: "https://i3.ytimg.com/vi/kZN2yTa1HcY/maxresdefault.jpg",
      name: "du lịch 5",
    },
  ]