"""fix migration

Revision ID: 2624f27fc11f
Revises: 5ab97698453f
Create Date: 2023-12-12 21:42:31.236289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2624f27fc11f'
down_revision: Union[str, None] = '5ab97698453f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('movies', sa.Column('date_of_release', sa.DateTime(), nullable=True))
    # op.add_column('movies', sa.Column('genre', sa.String(length=256), nullable=True))
    # op.drop_index('ix_movies_year_of_release', table_name='movies')
    # op.create_index(op.f('ix_movies_date_of_release'), 'movies', ['date_of_release'], unique=False)
    # op.create_index(op.f('ix_movies_genre'), 'movies', ['genre'], unique=False)
    # op.drop_column('movies', 'year_of_release')
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('year_of_release', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_movies_genre'), table_name='movies')
    op.drop_index(op.f('ix_movies_date_of_release'), table_name='movies')
    op.create_index('ix_movies_year_of_release', 'movies', ['year_of_release'], unique=False)
    op.drop_column('movies', 'genre')
    op.drop_column('movies', 'date_of_release')
    # ### end Alembic commands ###
