"""Change time stamps to created_at

Revision ID: 5ab97698453f
Revises: 5b9d928266c3
Create Date: 2023-12-12 21:39:02.109539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5ab97698453f'
down_revision: Union[str, None] = '5b9d928266c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('moviecomments', sa.Column('created_at', sa.DateTime(), nullable=True))
    # op.drop_index('ix_moviecomments_day_of_comment', table_name='moviecomments')
    # op.drop_index('ix_moviecomments_month_of_comment', table_name='moviecomments')
    # op.drop_index('ix_moviecomments_year_of_comment', table_name='moviecomments')
    # op.create_index(op.f('ix_moviecomments_created_at'), 'moviecomments', ['created_at'], unique=False)
    # op.drop_column('moviecomments', 'year_of_comment')
    # op.drop_column('moviecomments', 'month_of_comment')
    # op.drop_column('moviecomments', 'day_of_comment')
    # op.add_column('movielists', sa.Column('created_at', sa.DateTime(), nullable=True))
    # op.drop_index('ix_movielists_day_of_creation', table_name='movielists')
    # op.drop_index('ix_movielists_month_of_creation', table_name='movielists')
    # op.drop_index('ix_movielists_year_of_creation', table_name='movielists')
    # op.create_index(op.f('ix_movielists_created_at'), 'movielists', ['created_at'], unique=False)
    # op.drop_column('movielists', 'day_of_creation')
    # op.drop_column('movielists', 'year_of_creation')
    # op.drop_column('movielists', 'month_of_creation')
    # op.add_column('movieratings', sa.Column('created_at', sa.DateTime(), nullable=True))
    # op.drop_index('ix_movieratings_day_of_rating', table_name='movieratings')
    # op.drop_index('ix_movieratings_month_of_rating', table_name='movieratings')
    # op.drop_index('ix_movieratings_year_of_rating', table_name='movieratings')
    # op.create_index(op.f('ix_movieratings_created_at'), 'movieratings', ['created_at'], unique=False)
    # op.drop_column('movieratings', 'month_of_rating')
    # op.drop_column('movieratings', 'day_of_rating')
    # op.drop_column('movieratings', 'year_of_rating')
    # op.add_column('movieviews', sa.Column('created_at', sa.DateTime(), nullable=True))
    # op.drop_index('ix_movieviews_day_of_view', table_name='movieviews')
    # op.drop_index('ix_movieviews_month_of_view', table_name='movieviews')
    # op.drop_index('ix_movieviews_year_of_view', table_name='movieviews')
    # op.create_index(op.f('ix_movieviews_created_at'), 'movieviews', ['created_at'], unique=False)
    # op.drop_column('movieviews', 'month_of_view')
    # op.drop_column('movieviews', 'year_of_view')
    # op.drop_column('movieviews', 'day_of_view')
    # op.add_column('users', sa.Column('time_of_birth', sa.Integer(), nullable=True))
    # op.drop_index('ix_users_day_of_birth', table_name='users')
    # op.drop_index('ix_users_month_of_birth', table_name='users')
    # op.drop_index('ix_users_year_of_birth', table_name='users')
    # op.create_index(op.f('ix_users_time_of_birth'), 'users', ['time_of_birth'], unique=False)
    # op.drop_column('users', 'day_of_birth')
    # op.drop_column('users', 'year_of_birth')
    # op.drop_column('users', 'month_of_birth')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('month_of_birth', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('year_of_birth', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('day_of_birth', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_time_of_birth'), table_name='users')
    op.create_index('ix_users_year_of_birth', 'users', ['year_of_birth'], unique=False)
    op.create_index('ix_users_month_of_birth', 'users', ['month_of_birth'], unique=False)
    op.create_index('ix_users_day_of_birth', 'users', ['day_of_birth'], unique=False)
    op.drop_column('users', 'time_of_birth')
    op.add_column('movieviews', sa.Column('day_of_view', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('movieviews', sa.Column('year_of_view', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('movieviews', sa.Column('month_of_view', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_movieviews_created_at'), table_name='movieviews')
    op.create_index('ix_movieviews_year_of_view', 'movieviews', ['year_of_view'], unique=False)
    op.create_index('ix_movieviews_month_of_view', 'movieviews', ['month_of_view'], unique=False)
    op.create_index('ix_movieviews_day_of_view', 'movieviews', ['day_of_view'], unique=False)
    op.drop_column('movieviews', 'created_at')
    op.add_column('movieratings', sa.Column('year_of_rating', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('movieratings', sa.Column('day_of_rating', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('movieratings', sa.Column('month_of_rating', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_movieratings_created_at'), table_name='movieratings')
    op.create_index('ix_movieratings_year_of_rating', 'movieratings', ['year_of_rating'], unique=False)
    op.create_index('ix_movieratings_month_of_rating', 'movieratings', ['month_of_rating'], unique=False)
    op.create_index('ix_movieratings_day_of_rating', 'movieratings', ['day_of_rating'], unique=False)
    op.drop_column('movieratings', 'created_at')
    op.add_column('movielists', sa.Column('month_of_creation', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('movielists', sa.Column('year_of_creation', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('movielists', sa.Column('day_of_creation', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_movielists_created_at'), table_name='movielists')
    op.create_index('ix_movielists_year_of_creation', 'movielists', ['year_of_creation'], unique=False)
    op.create_index('ix_movielists_month_of_creation', 'movielists', ['month_of_creation'], unique=False)
    op.create_index('ix_movielists_day_of_creation', 'movielists', ['day_of_creation'], unique=False)
    op.drop_column('movielists', 'created_at')
    op.add_column('moviecomments', sa.Column('day_of_comment', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('moviecomments', sa.Column('month_of_comment', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('moviecomments', sa.Column('year_of_comment', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_moviecomments_created_at'), table_name='moviecomments')
    op.create_index('ix_moviecomments_year_of_comment', 'moviecomments', ['year_of_comment'], unique=False)
    op.create_index('ix_moviecomments_month_of_comment', 'moviecomments', ['month_of_comment'], unique=False)
    op.create_index('ix_moviecomments_day_of_comment', 'moviecomments', ['day_of_comment'], unique=False)
    op.drop_column('moviecomments', 'created_at')
    # ### end Alembic commands ###
