"""fix migration

Revision ID: 89c8106e5547
Revises: 92a727e86752
Create Date: 2023-12-12 21:59:29.709401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '89c8106e5547'
down_revision: Union[str, None] = '92a727e86752'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('movies', sa.Column('thumbnail_id', sa.String(length=256), nullable=True))
    # op.drop_column('movies', 'thumbnail_url')
    # op.add_column('users', sa.Column('avatar_id', sa.String(length=256), nullable=True))
    # op.drop_column('users', 'avatar_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_url', mysql.VARCHAR(length=256), nullable=True))
    op.drop_column('users', 'avatar_id')
    op.add_column('movies', sa.Column('thumbnail_url', mysql.VARCHAR(length=256), nullable=True))
    op.drop_column('movies', 'thumbnail_id')
    # ### end Alembic commands ###
