"""change user date_of_birth field

Revision ID: 63995d6627c0
Revises: 89c8106e5547
Create Date: 2023-12-17 23:44:11.727029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '63995d6627c0'
down_revision: Union[str, None] = '89c8106e5547'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('date_of_birth', sa.DateTime(), nullable=True))
    op.drop_index('ix_users_time_of_birth', table_name='users')
    op.create_index(op.f('ix_users_date_of_birth'), 'users', ['date_of_birth'], unique=False)
    op.drop_column('users', 'time_of_birth')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('time_of_birth', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_date_of_birth'), table_name='users')
    op.create_index('ix_users_time_of_birth', 'users', ['time_of_birth'], unique=False)
    op.drop_column('users', 'date_of_birth')
    # ### end Alembic commands ###
