"""change image ids to url

Revision ID: 7fc39262d42f
Revises: 8539462c70b3
Create Date: 2023-12-31 12:31:02.413083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7fc39262d42f'
down_revision: Union[str, None] = '8539462c70b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('thumbnail_url', sa.String(length=512), nullable=True))
    op.drop_column('movies', 'thumbnail_id')
    op.add_column('users', sa.Column('avatar_url', sa.String(length=512), nullable=True))
    op.drop_column('users', 'avatar_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_id', mysql.VARCHAR(length=256), nullable=True))
    op.drop_column('users', 'avatar_url')
    op.add_column('movies', sa.Column('thumbnail_id', mysql.VARCHAR(length=256), nullable=True))
    op.drop_column('movies', 'thumbnail_url')
    # ### end Alembic commands ###
