"""add movie subgenre

Revision ID: 8539462c70b3
Revises: cb4f08320449
Create Date: 2023-12-29 21:32:44.863558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8539462c70b3'
down_revision: Union[str, None] = 'cb4f08320449'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('subgenre', sa.String(length=256), nullable=True))
    op.create_index(op.f('ix_movies_subgenre'), 'movies', ['subgenre'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movies_subgenre'), table_name='movies')
    op.drop_column('movies', 'subgenre')
    # ### end Alembic commands ###
