"""add source to movie

Revision ID: cb4f08320449
Revises: 3037e553e188
Create Date: 2023-12-27 23:10:35.551390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb4f08320449'
down_revision: Union[str, None] = '3037e553e188'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('source', sa.String(length=256), nullable=True))
    op.create_index(op.f('ix_movies_source'), 'movies', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movies_source'), table_name='movies')
    op.drop_column('movies', 'source')
    # ### end Alembic commands ###
